curl/curl-fuzzer

ossfuzz.sh, scripts/check_i386.sh, scripts/download_zlib.sh, scripts/install_zlib.sh, scripts/ossfuzzdeps.sh
In i386 mode we need to compile zlib into the fuzzer.
=> i386: compile zlib into the fuzzer

curl_fuzzer_tlv.cc
Discovered by OSS-Fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16703
=> Use uint64_ts for comparing TLV lengths.

curl_fuzzer.h, curl_fuzzer_tlv.cc
I managed to get the functions in doh.c exercised with this branch. It would be nice to see oss-fuzz cover also that function.
If you merge soon, it will be interesting to see if oss-fuzz finds the bug in https://github.com/curl/curl/pull/4352 before it has been merged into master. It may be difficult to randomly come up with a 480 something input while also matching the TLV and length, but let's see!
=> add use of dns over https (doh)

corpus.py
This means we can understand what TLV type 41 is when decoding.
=> Add the DOH_URL type to corpus.py

ossfuzz.sh
OpenSSL is not clean under the memory sanitizer, so disable it in oss-fuzz memory sanitizer builds.
=> Disable Openssl for memory sanitizer

curl_fuzzer.h, curl_fuzzer_callback.cc
This prevents certain highly compressed payloads from timing out the fuzzer.
=> fuzzer: Set a maximum write length for the fuzzer

ossfuzz.sh
The Apache license was mistakenly applied to this file. Replace it with the standard curl
license header.
Closes #49
Signed-off-by: Max Dymond <cmeister2@gmail.com>
=> Replace Apache license with curl license.

curl_fuzzer_tlv.cc
The CURLOPT_HSTS TLV causes randomly named files to be generated in the output folder when running the fuzzer. This causes issues with the overall oss-fuzz build. Removing this until we can decide how to fix the issue properly
=> Temporarily remove the option to specify the CURLOPT_HSTS TLV

.github/workflows/ci.yml
We're slightly abusing the CIFuzz interface here to parallelize fuzzing across a number of parallel jobs by only extracting one fuzzer in a given job.
=> Use massively parallel CI

scripts/install_openssl.sh
Use the `no-threads` option like the oss-fuzz version of OpenSSL
=> scripts: Fix openssl build in i386 mode

curl_fuzzer_tlv.cc
`curl_slist_append` can return NULL, especially when there is an allocation failure inside it...
In this case, ignore the addition of the new value (another option would be to go to `EXIT_LABEL` with some `rc` value for an error code)
This was found by POC nallocfuzz...
=> tlv: do not leak on allocation failure in curl_slist_append

curl_fuzzer_tlv.cc
As in commit e13aa01d58a1b082f7bcb8ef07245decac35b193
Found by quadfuzz
=> ossfuzz: Prevent large numbers of recipients from causing timeouts

curl_fuzzer_tlv.cc
Compeltes previous commit
@bagder we went too fast with previous PR #75 ;-)
=> ossfuzz: Prevent large numbers of headers from causing timeouts

ossfuzz.sh
Compiling GDB on its own doesn't really do much if you don't also drop the level of optimisation. Testing seems to indicate a level of -O0 to give the best results.
To trigger this behaviour you can either call `export GDBMODE=1` before running `compile` in a `shell` environment, or call the infra/helper as
```bash
python infra/helper.py shell --architecture <arch> --sanitizer <sanitizer> -e GDBMODE=1 curl
```
=> Detect GDBMODE and compile fuzz targets appropriately

scripts/install_openssl.sh
libssl.a is installed on `$PREFIX/lib64/` on x86_64 builds, and the scripts here are not aware of this location. Always use `$PREFIX/lib/` to keep things uniform.
=> scripts: fix ssl builds on x86_64

scripts/download_nghttp2.sh
Working on https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44517
that triggers an issue in nghttp2 we want to make sure it isn't due to a
problem in an old release.
=> scripts/download_nghttp2.sh: clone 1.58.0

.github/workflows/ci.yml
The new v4 artifact snippets are flaky. See https://github.com/actions/download-artifact/issues/249.
Reverting until stable.
=> Temporarily revert artifact snippets @4

scripts/VERSIONS
Unfortunately renovate doesn't allow us to try these things without being in the `main` branch, which is bizarre, but hopefully once it's finished it's done for good.
=> Instead of extractVersion, try a regex versioning scheme.

renovate.json
Group the `upload-artifact` and `download-artifact` packages together
=> renovate: Group artifact packages together

scripts/install_curl.sh
It will soon cause a configure error if not found when not explicitly disabled.
=> scripts/install_curl.sh: explicitly disable use of libpsl

curl_fuzzer_callback.cc, curl_fuzzer_tlv.cc, fuzz_bufq.cc
These warnings and errors were observed on today's OSS-Fuzz build logs[1] and mostly concern the different type widths on i386.
[1]: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#curl
=> Resolve i386 build warnings and errors

scripts/VERSIONS, scripts/download_nghttp2.sh, scripts/download_openssl.sh
Renovate doesn't add prefixes to versions - so add them in the scripts instead
=> Just use the bare versions in the versions file.

renovate.json
Renovate isn't picking up openssl again. Fix it so it does.
=> renovate: Fix openssl versioning

Makefile.am
To avoid getting deprecation warnings we don't care about all over the terminal output.
=> Makefile.am: pass -DCURL_DISABLE_DEPRECATION to the compiler

Makefile.am
The build can easily break and require a manual 'make libstandaloneengine.a' without this precaution that makes sure the lib is built first.
Ref: #19
=> Makefile: make sure libstandaloneengine gets built first

DEBIAN.md
Just a simple guide to getting the fuzzer to build and run on current debian unstable
Fixes #19
=> DEBIAN: running curl-fuzzer on Debian Unstable

.github/workflows/ci.yml, CMakeLists.txt, scripts/compile_target.sh
In order to regressibly test the i386 build, add it as an architecture option.
=> Add i386 test build

scripts/ossfuzzdeps.sh
LDAP needs this installed, so we have a two step process whereby this needs to be in master before it gets picked up by CI. Slightly tedious but ok.
=> ci: Add groff-base as a dependency to install

CMakeLists.txt
Ref: https://www.openldap.org/software/download/
Note: new releases may not be available on the mirrors.
```
CMake Error at openldap_external-stamp/download-openldap_external.cmake:163 (message):
Each download failed!
error: downloading 'https://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-2.6.10.tgz' failed
status_code: 28
status_string: "Timeout was reached"
log:
--- LOG BEGIN ---
timeout on name lookup is not supported
```
Ref: https://github.com/curl/curl/actions/runs/17893469923/job/50876989019?pr=18660#step:4:1523
=> cmake: add mirror for the openldap tarball
